/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.nbandroid.netbeans.gradle.v2.layout.layout;

import java.io.File;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JPanel;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.netbeans.core.spi.multiview.text.MultiViewEditorElement;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import sk.arsi.netbeans.gradle.android.layout.spi.LayoutPreviewProvider;

/**
 *
 * @author arsi
 */
@MultiViewElement.Registration(
        displayName = "&Preview",
        iconBase = "org/nbandroid/netbeans/gradle/v2/layout/layout/activity.png",
        mimeType = "text/x-android-layout+xml",
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED,
        preferredID = "preview",
        position = 2
)
public class LayoutPreviewElement extends TopComponent implements MultiViewElement {

    private transient MultiViewElementCallback callback;
    private LayoutDataObject dataObject;
    private MultiViewEditorElement editorElement;

    /**
     * Creates new form LayoutPreviewElement
     */
    public LayoutPreviewElement() {
        initComponents();
    }

    public LayoutPreviewElement(Lookup lkp) {
        initComponents();
        dataObject = lkp.lookup(LayoutDataObject.class);
        editorElement = new MultiViewEditorElement(dataObject.getLookup());
        JComponent visualRepresentation = editorElement.getComponent();
        editorPanel.add(visualRepresentation);
        editorPanel.invalidate();
        editorPanel.repaint();

        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                try {
                    LayoutPreviewProvider previewProvider = Lookup.getDefault().lookup(LayoutPreviewProvider.class);
                    final JPanel panel = previewProvider.getPreview(new File("/jetty/android-studio-sdk/platforms/android-27"),
                            new File("/projekty/opensource/layoutlib-demo-2/res/testApp/MyApplication/src/main/res/layout/simple_activity.xml"),
                            new File("/projekty/opensource/layoutlib-demo-2/res/testApp/MyApplication/src/main/res"), "AppTheme");
                    Runnable runnable1 = new Runnable() {
                        @Override
                        public void run() {
                            if (panel != null) {
                                split.setRightComponent(panel);
                            }
                            split.revalidate();
                        }
                    };
                    WindowManager.getDefault().invokeWhenUIReady(runnable1);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        };
        new Thread(runnable).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        split = new javax.swing.JSplitPane();
        editorPanel = new javax.swing.JPanel();

        toolbar.setRollover(true);

        split.setDividerLocation(400);
        split.setDividerSize(5);

        editorPanel.setLayout(new java.awt.CardLayout());
        split.setLeftComponent(editorPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JComponent getVisualRepresentation() {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() {
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return editorElement.getActions(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Lookup getLookup() {
        return new ProxyLookup(editorElement.getLookup());
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback callback) {
        this.callback = callback;
        callback.getTopComponent().setDisplayName(dataObject.getName());
        editorElement.setMultiViewCallback(callback);
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }

    @Override
    public void componentActivated() {
        super.componentActivated();
//        Container parent = this.getParent().getParent().getParent();
//        try {
//            Field field = parent.getClass().getDeclaredField("alreadyAddedElements");
//            field.setAccessible(true);
//            List<MultiViewElement> tmp = new ArrayList<>((Set<MultiViewElement>) field.get(parent));
//            for (MultiViewElement el : tmp) {
//                if (el instanceof MultiViewEditorElement) {
//                    editorElement = (MultiViewEditorElement) el;
//                    editorPanel.add(editorElement.getVisualRepresentation());
//                    editorPanel.invalidate();
//                    editorPanel.repaint();
//                    editorElement.componentActivated();
//                }
//            }
//
//            System.out.println("org.nbandroid.netbeans.gradle.v2.layout.layout.LayoutPreviewElement.componentActivated()");
//        } catch (NoSuchFieldException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (SecurityException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (IllegalArgumentException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (IllegalAccessException ex) {
//            Exceptions.printStackTrace(ex);
//        }

        editorElement.componentActivated();
    }

    @Override
    public void componentDeactivated() {
        super.componentDeactivated();
        editorElement.componentDeactivated();
    }

    @Override
    public void componentHidden() {
        super.componentHidden(); //To change body of generated methods, choose Tools | Templates.
        editorElement.componentHidden();
    }

    @Override
    public void componentShowing() {
        super.componentShowing(); //To change body of generated methods, choose Tools | Templates.
        editorElement.componentShowing();
    }

    @Override
    public void componentClosed() {
        super.componentClosed(); //To change body of generated methods, choose Tools | Templates.
        editorElement.componentClosed();
    }

    @Override
    public void componentOpened() {
        super.componentOpened(); //To change body of generated methods, choose Tools | Templates.
        editorElement.componentOpened();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editorPanel;
    private javax.swing.JSplitPane split;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public UndoRedo getUndoRedo() {
        return editorElement.getUndoRedo();
    }

}
