/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.netbeans.modules.android.project.ui.customizer;

import java.io.File;
import org.netbeans.modules.android.project.JarLibsModel;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.openide.filesystems.FileChooserBuilder;

/** 
 * Customizer for Android libraries.
 */
public class CustomizerJARs extends JPanel {
  private static final Logger LOG = Logger.getLogger(CustomizerJARs.class.getName());

  private final DefaultTableModel libsTableModel;
  private final JarLibsModel jarLibsModel;

  public CustomizerJARs(JarLibsModel jarLibsModel) {
    this.jarLibsModel = jarLibsModel;

    libsTableModel = new javax.swing.table.DefaultTableModel(
        new String[0][],
        new String [] {"JAR"}) {
      Class[] types = new Class [] {String.class};
      boolean[] canEdit = new boolean [] {false};

      @Override
      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      @Override
      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    };
    initComponents(); 
    initFromProject();
    jTextFieldLibsFolder.getDocument().addDocumentListener(new DocumentListener() {

      @Override
      public void insertUpdate(DocumentEvent e) {
        updateData();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        updateData();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        updateData();
      }
    });
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJARs = new javax.swing.ButtonGroup();
        jLabelReferrencedJARs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibs = new javax.swing.JTable();
        jRadioButtonDefault = new javax.swing.JRadioButton();
        jRadioButtonCustom = new javax.swing.JRadioButton();
        jLabelLibsFolder = new javax.swing.JLabel();
        jTextFieldLibsFolder = new javax.swing.JTextField();
        jButtonLibsFolderBrowse = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabelReferrencedJARs, "Referenced JAR libraries:");

        jTableLibs.setModel(libsTableModel);
        jTableLibs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableLibs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLibs);

        buttonGroupJARs.add(jRadioButtonDefault);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonDefault, "Default location (libs folder in your project)");
        jRadioButtonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDefaultActionPerformed(evt);
            }
        });

        buttonGroupJARs.add(jRadioButtonCustom);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButtonCustom, "Custom location");
        jRadioButtonCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelLibsFolder, "Location of JAR libraries");

        org.openide.awt.Mnemonics.setLocalizedText(jButtonLibsFolderBrowse, "Browse");
        jButtonLibsFolderBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLibsFolderBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLibsFolder)
                    .addComponent(jLabelReferrencedJARs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCustom)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldLibsFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLibsFolderBrowse))
                            .addComponent(jRadioButtonDefault))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLibsFolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibsFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCustom)
                    .addComponent(jButtonLibsFolderBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReferrencedJARs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void jRadioButtonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDefaultActionPerformed
    updateData();
  }//GEN-LAST:event_jRadioButtonDefaultActionPerformed

  private void jRadioButtonCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomActionPerformed
    updateData();
  }//GEN-LAST:event_jRadioButtonCustomActionPerformed

  private void jButtonLibsFolderBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLibsFolderBrowseActionPerformed
    File libsDirectory = new FileChooserBuilder(CustomizerJARs.class)
        .setDirectoriesOnly(true)
        .setTitle("Select directory with JAR libraries")
        .showOpenDialog();
    if (libsDirectory != null) {
      jTextFieldLibsFolder.setText(libsDirectory.getAbsolutePath());
      updateData();
    }

  }//GEN-LAST:event_jButtonLibsFolderBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJARs;
    private javax.swing.JButton jButtonLibsFolderBrowse;
    private javax.swing.JLabel jLabelLibsFolder;
    private javax.swing.JLabel jLabelReferrencedJARs;
    private javax.swing.JRadioButton jRadioButtonCustom;
    private javax.swing.JRadioButton jRadioButtonDefault;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibs;
    private javax.swing.JTextField jTextFieldLibsFolder;
    // End of variables declaration//GEN-END:variables

  private void initFromProject() {
    jRadioButtonDefault.setSelected(jarLibsModel.isUseDefaultLocation());
    jRadioButtonCustom.setSelected(!jarLibsModel.isUseDefaultLocation());
    jTextFieldLibsFolder.setText(
        jarLibsModel.isUseDefaultLocation() ? "" : jarLibsModel.getLibsDir());
    updateData();
  }

  private void updateData() {
    jarLibsModel.setUseDefaultLocation(jRadioButtonDefault.isSelected());
    jarLibsModel.setLibsDir(jTextFieldLibsFolder.getText());

    jTextFieldLibsFolder.setEnabled(!jarLibsModel.isUseDefaultLocation());
    jButtonLibsFolderBrowse.setEnabled(!jarLibsModel.isUseDefaultLocation());

    libsTableModel.setRowCount(0);
    for (String library : jarLibsModel.getLibNames()) {
      libsTableModel.addRow(new String[] {library});
    }
  }
}
