package org.nbandroid.netbeans.gradle.ui;

import org.nbandroid.netbeans.gradle.config.AndroidTestRunConfiguration;
import org.openide.awt.*;

/**
 *
 * @author radim
 */
public class AndroidTestsPanel extends javax.swing.JPanel {

  /**
   * Creates new form BuildCustomizerPanel
   */
  public AndroidTestsPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    runnerLabel = new javax.swing.JLabel();
    runnerCombo = new javax.swing.JComboBox();

    org.openide.awt.Mnemonics.setLocalizedText(runnerLabel, org.openide.util.NbBundle.getMessage(AndroidTestsPanel.class, "AndroidTestsPanel.runnerLabel.text")); // NOI18N

    runnerCombo.setEditable(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(runnerCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(runnerLabel)
            .addGap(0, 134, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(runnerLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(runnerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(237, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox runnerCombo;
  private javax.swing.JLabel runnerLabel;
  // End of variables declaration//GEN-END:variables

  void setData(AndroidTestRunConfiguration testCfg) {
    String runner = testCfg.getTestRunner();
    runnerCombo.setSelectedItem(runner != null ? runner : "");
  }
  
  
  String getData() {
    return (String) runnerCombo.getSelectedItem();
  }
}
