/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.nbandroid.netbeans.gradle.v2.project.template;

import android.studio.imports.templates.Template;
import android.studio.imports.templates.TemplateManager;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JPanel;
import static org.nbandroid.netbeans.gradle.v2.project.template.AndroidProjectTemplatePanelVisualAndroidSettings.PROP_MAX_BUILD_LEVEL;
import static org.nbandroid.netbeans.gradle.v2.project.template.AndroidProjectTemplatePanelVisualAndroidSettings.PROP_PHONE_TABLET_PLATFORM;
import static org.nbandroid.netbeans.gradle.v2.project.template.AndroidProjectTemplatePanelVisualBasicSettings.PROP_PROJECT_SDK;
import org.nbandroid.netbeans.gradle.v2.sdk.AndroidSdk;
import org.nbandroid.netbeans.gradle.v2.sdk.PlatformDecorator;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;

public class AndroidProjectTemplatePanelMobileActivityAndroidSettings extends JPanel implements ItemListener, AndroidActivityTemplateHandler {

    private AndroidProjectTemplateWizardPanelMobileActivityAndroidSettings panel;
    public static final String PROP_MOBILE_TEMPLATE = "PROP_MOBILE_TEMPLATE";
    public static final String PROP_MOBILE_CONFIG = "PROP_MOBILE_CONFIG";
    private AndroidSdk androidSdk;
    private Template currentTemplate;

    public AndroidProjectTemplatePanelMobileActivityAndroidSettings(AndroidProjectTemplateWizardPanelMobileActivityAndroidSettings panel) {
        initComponents();
        this.panel = panel;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public Template getCurrentTemplate() {
        return currentTemplate;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activitysPanel = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AndroidProjectTemplatePanelMobileActivityAndroidSettings.class, "AndroidProjectTemplatePanelMobileActivityAndroidSettings.jLabel3.text")); // NOI18N

        activitysPanel.setBackground(new java.awt.Color(255, 255, 255));
        activitysPanel.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(activitysPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(503, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activitysPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
    }

    boolean valid(WizardDescriptor wizardDescriptor) {
        return true;
    }

    void store(WizardDescriptor d) {
        d.putProperty(PROP_MOBILE_TEMPLATE, currentTemplate);
    }

    void read(WizardDescriptor settings) {
        activitysPanel.removeAll();
        androidSdk = (AndroidSdk) settings.getProperty(PROP_PROJECT_SDK);
        currentTemplate = (Template) settings.getProperty(PROP_MOBILE_TEMPLATE);
        if (settings.getProperty(PROP_PHONE_TABLET_PLATFORM) instanceof PlatformDecorator) {
            PlatformDecorator platformInfo = (PlatformDecorator) settings.getProperty(PROP_PHONE_TABLET_PLATFORM);
            int minApiLevel = platformInfo.getAndroidVersion().getFeatureLevel();
            int buildApiLevel = (int) settings.getProperty(PROP_MAX_BUILD_LEVEL);
            List<Template> templates = TemplateManager.findActivityTemplates("Mobile", minApiLevel, buildApiLevel);
            activitysPanel.add(new NoActivityForm(this));
            for (Template template : templates) {
                activitysPanel.add(new ActivityForm(template, this));
            }
            Component[] components = activitysPanel.getComponents();
            for (Component component : components) {
                if (component instanceof AndroidActivityTemplateProvider) {
                    ((AndroidActivityTemplateProvider) component).select(currentTemplate);
                }
            }
        }

    }

    @Override
    public void setCurrentTemplate(Template currentTemplate) {
        this.currentTemplate = currentTemplate;
        panel.fireChangeEvent();
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        panel.fireChangeEvent();
    }

    void validate(WizardDescriptor d) throws WizardValidationException {
        // nothing to validate
    }
}
