/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nbandroid.netbeans.gradle.v2.project.template;

import android.studio.imports.templates.Template;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.Objects;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import org.openide.filesystems.FileObject;
import org.openide.util.Exceptions;

/**
 *
 * @author arsi
 */
public class ActivityForm extends javax.swing.JPanel implements MouseListener, FocusListener, AndroidActivityTemplateProvider {

    private final Template template;
    private final AndroidProjectTemplatePanelMobileActivityAndroidSettings androidSettings;
    /**
     * Creates new form ActivityForm
     */
    Border borderOn = BorderFactory.createLineBorder(Color.blue, 1);
    Border borderOff = BorderFactory.createLineBorder(Color.lightGray, 1);

    public ActivityForm(Template template, AndroidProjectTemplatePanelMobileActivityAndroidSettings androidSettings) {
        initComponents();
        this.androidSettings = androidSettings;
        this.template = template;
        title.setText(template.getMetadata().getTitle());
        String thumbnailPath = template.getMetadata().getThumbnailPath();
        FileObject fileObject = template.getFileObject();
        FileObject thumbnail = fileObject.getParent().getFileObject(thumbnailPath);
        try {
            image.setIcon(new ImageIcon(thumbnail.asBytes()));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        if (template.getMetadata().getDescription() != null) {
            image.setToolTipText(template.getMetadata().getDescription());
        }
        addMouseListener(this);
        image.addMouseListener(this);
        setBorder(null);
        setFocusable(true);
        setRequestFocusEnabled(true);
        addFocusListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        image = new org.nbandroid.netbeans.gradle.v2.project.template.ImageLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(280, 290));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(title, org.openide.util.NbBundle.getMessage(ActivityForm.class, "ActivityForm.title.text")); // NOI18N
        title.setOpaque(true);

        image.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(image, org.openide.util.NbBundle.getMessage(ActivityForm.class, "ActivityForm.image.text")); // NOI18N
        image.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.nbandroid.netbeans.gradle.v2.project.template.ImageLabel image;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
        requestFocusInWindow(true);
        setBorder(borderOn);
        title.setBackground(Color.blue);
        title.setForeground(Color.white);
        androidSettings.setCurrentTemplate(template);
    }

    @Override
    public void mousePressed(MouseEvent me) {
    }

    @Override
    public void mouseReleased(MouseEvent me) {
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }

    @Override
    public void focusGained(FocusEvent fe) {
       
    }

    @Override
    public Dimension getMaximumSize() {
        return new Dimension(280, 290); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(280, 290); //To change body of generated methods, choose Tools | Templates.
    }





    @Override
    public void focusLost(FocusEvent fe) {
        setBorder(null);
        title.setBackground(Color.white);
        title.setForeground(Color.black);
    }

    @Override
    public void select(Template template) {
        if(Objects.equals(template, this.template)){
            mouseClicked(null);
        }
    }
}
