/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbandroid.netbeans.gradle.options;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.nbandroid.netbeans.gradle.core.sdk.DalvikPlatformManager;
import org.openide.awt.HtmlBrowser.URLDisplayer;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.Exceptions;

final class AndroidPlatformPanel extends AndroidOptionsSubPanel {

  private final AndroidOptionsPanelController controller;
  private final DocumentListener docListener;

  AndroidPlatformPanel(AndroidOptionsPanelController controller) {
    this.controller = controller;
    initComponents();
    docListener = new DocumentListener() {

      @Override
      public void insertUpdate(DocumentEvent e) {
        AndroidPlatformPanel.this.controller.markChanged();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        AndroidPlatformPanel.this.controller.markChanged();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        AndroidPlatformPanel.this.controller.markChanged();
      }
    };
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelSdkLocation = new javax.swing.JLabel();
    jTextFieldSdkLocation = new javax.swing.JTextField();
    jButtonSdkLocatioBrowse = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    cbxStats = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();

    org.openide.awt.Mnemonics.setLocalizedText(jLabelSdkLocation, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jLabelSdkLocation.text")); // NOI18N

    jTextFieldSdkLocation.setText(org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jTextFieldSdkLocation.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jButtonSdkLocatioBrowse, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jButtonSdkLocatioBrowse.text")); // NOI18N
    jButtonSdkLocatioBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSdkLocatioBrowseActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jLabel1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jLabel2.text")); // NOI18N
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel2MouseClicked(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(cbxStats, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.cbxStats.text")); // NOI18N
    cbxStats.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbxStatsActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(AndroidPlatformPanel.class, "AndroidPlatformPanel.jButton1.text")); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelSdkLocation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldSdkLocation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonSdkLocatioBrowse))
          .addComponent(jSeparator1)
          .addComponent(cbxStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton1))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelSdkLocation)
          .addComponent(jTextFieldSdkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonSdkLocatioBrowse))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cbxStats)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(28, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonSdkLocatioBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSdkLocatioBrowseActionPerformed
    File sdkDir = new FileChooserBuilder(AndroidPlatformPanel.class)
        .setDirectoriesOnly(true)
        .setTitle("Choose Android SDK directory")
        .showOpenDialog();
    if (sdkDir != null) {
      jTextFieldSdkLocation.setText(sdkDir.getAbsolutePath());
    }
  }//GEN-LAST:event_jButtonSdkLocatioBrowseActionPerformed

  private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    try {
      URLDisplayer.getDefault().showURL(new URL("http://developer.android.com/sdk/index.html"));
    } catch (MalformedURLException ex) {
      Exceptions.printStackTrace(ex);
    }
  }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      URLDisplayer.getDefault().showURL(new URL("http://nbandroid.org/"));
    } catch (MalformedURLException ex) {
      Exceptions.printStackTrace(ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatsActionPerformed
        controller.setEnableStats(cbxStats.isSelected());
    }//GEN-LAST:event_cbxStatsActionPerformed

  @Override
  public void load() {
    if (docListener != null) {
      jTextFieldSdkLocation.getDocument().removeDocumentListener(docListener);
    }
    jTextFieldSdkLocation.setText(DalvikPlatformManager.getDefault().getSdkLocation());
    jTextFieldSdkLocation.getDocument().addDocumentListener(docListener);
    cbxStats.setSelected(controller.isEnableStats());
  }

  @Override
  public void store() {
    DalvikPlatformManager.getDefault().setSdkLocation(jTextFieldSdkLocation.getText());
  }

  @Override
  public boolean valid() {
    // TODO(radim): move this to a better place?
    File sdkLocation = new File(jTextFieldSdkLocation.getText());
    File sdkTools = new File(sdkLocation, "tools");
    return sdkLocation.exists() && sdkLocation.isDirectory() &&
        sdkTools.exists() && sdkTools.isDirectory();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox cbxStats;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButtonSdkLocatioBrowse;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabelSdkLocation;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextField jTextFieldSdkLocation;
  // End of variables declaration//GEN-END:variables
}
